services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.10
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "80:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-db}
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
    ports:
      - "5432:5432"
    volumes:
      - pg:/var/lib/postgresql/data

volumes:
  pg:
    driver: local
  pgadmin:
    driver: local
